### ISSUE TITLE
Find Images Dataset

### ISSUE THREAD

**Issue by kelvin2007** [Bam280/mendaur-app#4]
source : 
- https://www.kaggle.com/techsash/waste-classification-data 
- https://www.kaggle.com/datasets/asdasdasasdas/garbage-classification

**Comment by RIFFMBR20** [comment]
https://drive.google.com/drive/folders/1KRMgsTlWX-JwZXChYXqRWKikChYPPvx-?usp=sharing

**Comment by kelvin2007** [comment]
keknya yang label trash gk usah aja deh, soalnya agak random gitu gua liat, ada sampah organik, ada kemasan plastik, ada botol plastik @RIFFMBR20

**Comment by RIFFMBR20** [comment]
Okay vin, terus di goggle drivenya dalam bentuk zip aja atau gimana?

**Comment by kelvin2007** [comment]
zip aja kalau agak berat, toh ntar diekstrak jg klwpun bukan zip, btw rif, kalau di bahasa indonesiain, gua pakenya cardboard =kardus, glass = kaca, metal = besi, paper = kertas, plastic = plastik. nanti diubah aja jd b indo buat yg recycleablenya @RIFFMBR20

**Comment by kelvin2007** [comment]
kalau bisa sekalian bikin py buat nyoba ekstrak + baca doang kek yg di coursera biar ada yg bisa di push ke githubnya. Tapi, kalau gak bisa, bikin txt file aja buat kasih source + linknya, kalau mau pake list label jg boleh biar ada yg bisa di push ke githubnya
